# Generated by Django 5.2 on 2025-09-10 21:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa Kategorii')),
                ('disciplines', models.JSONField(default=list, verbose_name='Dyscypliny')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SportClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa Klubu')),
            ],
            options={
                'verbose_name': 'Klub',
                'verbose_name_plural': 'Kluby',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Imię')),
                ('surname', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('weight', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Waga (kg)')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Kobieta'), ('male', 'Mężczyzna')], max_length=6, null=True, verbose_name='Płeć')),
                ('categories', models.ManyToManyField(blank=True, related_name='players', to='kb_live.category', verbose_name='Kategorie')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='kb_live.sportclub', verbose_name='Klub')),
            ],
            options={
                'verbose_name': 'Zawodnik',
                'verbose_name_plural': 'Zawodnicy',
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PistolResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kettlebell_weight', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Waga kettlebell (kg)')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pistol_result', to='kb_live.player', verbose_name='Zawodnik')),
            ],
            options={
                'verbose_name': 'Wynik Pistol Squat',
                'verbose_name_plural': 'Wyniki Pistol Squat',
            },
        ),
        migrations.CreateModel(
            name='PullUpResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kettlebell_weight', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Waga kettlebell (kg)')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pull_up_result', to='kb_live.player', verbose_name='Zawodnik')),
            ],
            options={
                'verbose_name': 'Wynik Pull-Up',
                'verbose_name_plural': 'Wyniki Pull-Up',
            },
        ),
        migrations.CreateModel(
            name='SeeSawPressResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kettlebell_weight', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Waga kettlebell (kg)')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='see_saw_press_result', to='kb_live.player', verbose_name='Zawodnik')),
            ],
            options={
                'verbose_name': 'Wynik See-Saw Press',
                'verbose_name_plural': 'Wyniki See-Saw Press',
            },
        ),
        migrations.CreateModel(
            name='SnatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kettlebell_weight', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Waga kettlebell (kg)')),
                ('repetitions', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ilość powtórzeń')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snatch_result', to='kb_live.player', verbose_name='Zawodnik')),
            ],
            options={
                'verbose_name': 'Wynik Snatch',
                'verbose_name_plural': 'Wyniki Snatch',
            },
        ),
        migrations.CreateModel(
            name='SquatResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kettlebell_weight', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Waga kettlebell (kg)')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='squat_result', to='kb_live.player', verbose_name='Zawodnik')),
            ],
            options={
                'verbose_name': 'Wynik KB Squat (2xKB suma)',
                'verbose_name_plural': 'Wyniki KB Squat (2xKB suma)',
            },
        ),
        migrations.CreateModel(
            name='TGUResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kettlebell_weight', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Waga kettlebell (kg)')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tgu_result', to='kb_live.player', verbose_name='Zawodnik')),
            ],
            options={
                'verbose_name': 'Wynik Turkish Get-Up',
                'verbose_name_plural': 'Wyniki Turkish Get-Up',
            },
        ),
        migrations.CreateModel(
            name='CategoryPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('snatch', 'Snatch'), ('tgu', 'Turkish Get-Up'), ('squat', 'Kettlebell Squat (2xKB)'), ('see_saw_press', 'See-Saw Press (2xKB)'), ('pistol', 'Pistol Squat'), ('pull_up', 'Pull-Up')], max_length=32, verbose_name='Konkurencja')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Miejsce')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='kb_live.category', verbose_name='Kategoria')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='kb_live.player', verbose_name='Zawodnik')),
            ],
            options={
                'verbose_name': 'Miejsce w kategorii',
                'verbose_name_plural': 'Miejsca w kategoriach',
                'ordering': ['category', 'discipline', 'position', 'player_id'],
                'indexes': [models.Index(fields=['category', 'discipline', 'position'], name='kb_live_cat_categor_5d4337_idx'), models.Index(fields=['discipline', 'player'], name='kb_live_cat_discipl_6b1e00_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'discipline', 'player'), name='uniq_category_discipline_player')],
            },
        ),
        migrations.CreateModel(
            name='PlayerCategoryTiebreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiebreaks_applied', to='kb_live.category', verbose_name='Kategoria')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiebreaks_applied', to='kb_live.player', verbose_name='Zawodnik')),
            ],
            options={
                'verbose_name': 'Zastosowany Tiebreak (Zawodnik-Kategoria)',
                'verbose_name_plural': 'Zastosowane Tiebreaki (Zawodnik-Kategoria)',
                'ordering': ['player__surname', 'player__name', 'category__name'],
                'indexes': [models.Index(fields=['category'], name='kb_live_pla_categor_8ad3e7_idx'), models.Index(fields=['player'], name='kb_live_pla_player__b2db77_idx')],
                'unique_together': {('player', 'category')},
            },
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['surname', 'name'], name='kb_live_pla_surname_0a27c2_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['gender'], name='kb_live_pla_gender_98360e_idx'),
        ),
    ]
