# Generated by Django 5.2 on 2025-09-10 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb_live', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOverallResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snatch_points', models.FloatField(blank=True, null=True, verbose_name='Punkty Snatch')),
                ('tgu_points', models.FloatField(blank=True, null=True, verbose_name='Punkty TGU')),
                ('squat_points', models.FloatField(blank=True, null=True, verbose_name='Punkty Squat')),
                ('see_saw_press_points', models.FloatField(blank=True, null=True, verbose_name='Punkty See-Saw')),
                ('pistol_points', models.FloatField(blank=True, null=True, verbose_name='Punkty Pistol')),
                ('pull_up_points', models.FloatField(blank=True, null=True, verbose_name='Punkty Pull-Up')),
                ('tiebreak_points', models.FloatField(default=0.0, verbose_name='Punkty Tiebreak')),
                ('total_points', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Suma Punktów')),
                ('final_position', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Miejsce Końcowe')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_results', to='kb_live.category', verbose_name='Kategoria')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_results', to='kb_live.player', verbose_name='Zawodnik')),
            ],
            options={
                'verbose_name': 'Wynik Ogólny Kategorii',
                'verbose_name_plural': 'Wyniki Ogólne Kategorii',
                'ordering': ['category', 'final_position', '-total_points'],
                'indexes': [models.Index(fields=['category', 'final_position'], name='kb_live_cat_categor_4a3253_idx'), models.Index(fields=['category', 'total_points'], name='kb_live_cat_categor_d86cfc_idx'), models.Index(fields=['player', 'category'], name='kb_live_cat_player__204779_idx')],
                'unique_together': {('player', 'category')},
            },
        ),
    ]

