# Generated by Django 5.2 on 2025-09-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb_live', '0002_categoryoverallresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryoverallresult',
            options={'ordering': ['category', 'final_position', 'total_points'], 'verbose_name': 'Wynik Ogólny Kategorii', 'verbose_name_plural': 'Wyniki Ogólne Kategorii'},
        ),
        migrations.RemoveField(
            model_name='pistolresult',
            name='kettlebell_weight',
        ),
        migrations.RemoveField(
            model_name='pullupresult',
            name='kettlebell_weight',
        ),
        migrations.RemoveField(
            model_name='seesawpressresult',
            name='kettlebell_weight',
        ),
        migrations.RemoveField(
            model_name='squatresult',
            name='kettlebell_weight',
        ),
        migrations.RemoveField(
            model_name='tguresult',
            name='kettlebell_weight',
        ),
        migrations.AddField(
            model_name='pistolresult',
            name='attempt_1',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Próba 1'),
        ),
        migrations.AddField(
            model_name='pistolresult',
            name='attempt_2',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Próba 2'),
        ),
        migrations.AddField(
            model_name='pistolresult',
            name='attempt_3',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Próba 3'),
        ),
        migrations.AddField(
            model_name='pullupresult',
            name='attempt_1',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Próba 1'),
        ),
        migrations.AddField(
            model_name='pullupresult',
            name='attempt_2',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Próba 2'),
        ),
        migrations.AddField(
            model_name='pullupresult',
            name='attempt_3',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Próba 3'),
        ),
        migrations.AddField(
            model_name='seesawpressresult',
            name='attempt_1',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Próba 1'),
        ),
        migrations.AddField(
            model_name='seesawpressresult',
            name='attempt_2',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Próba 2'),
        ),
        migrations.AddField(
            model_name='seesawpressresult',
            name='attempt_3',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Próba 3'),
        ),
        migrations.AddField(
            model_name='squatresult',
            name='attempt_1',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Próba 1'),
        ),
        migrations.AddField(
            model_name='squatresult',
            name='attempt_2',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Próba 2'),
        ),
        migrations.AddField(
            model_name='squatresult',
            name='attempt_3',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Próba 3'),
        ),
        migrations.AddField(
            model_name='tguresult',
            name='attempt_1',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Próba 1'),
        ),
        migrations.AddField(
            model_name='tguresult',
            name='attempt_2',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Próba 2'),
        ),
        migrations.AddField(
            model_name='tguresult',
            name='attempt_3',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Próba 3'),
        ),
        migrations.AlterField(
            model_name='categoryoverallresult',
            name='total_points',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Suma Miejsc'),
        ),
    ]
