# Generated by Django 5.2 on 2025-09-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb_live', '0003_alter_categoryoverallresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_counted_disciplines',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ile najlepszych wyników (najniższe miejsca) wliczać do sumy. Pozostaw puste aby liczyć wszystkie.', null=True, verbose_name='Liczba punktowanych konkurencji'),
        ),
    ]
