# Generated by Django 5.2 on 2025-09-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb_live', '0004_category_max_counted_disciplines'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoverallresult',
            name='counted_disciplines',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ile wyników wliczono do sumy miejsc w danym przeliczeniu.', verbose_name='Liczba zaliczonych konkurencji'),
        ),
    ]
