# Generated by Django 5.2 on 2025-09-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb_live', '0005_categoryoverallresult_counted_disciplines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(blank=True, choices=[('Kobieta', 'Kobieta'), ('Mężczyzna', 'Mężczyzna')], max_length=10, null=True, verbose_name='Płeć'),
        ),
    ]
